"""initial_schema

Revision ID: 4cfcf1cf520e
Revises: 
Create Date: 2026-09-15

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cfcf1cf520e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use synchronous connection for DDL statements that do not return rows
    from alembic import op
    import sqlalchemy as sa
    conn = op.get_bind()
    for stmt in [
        """CREATE TYPE public.assignableentitytype AS ENUM (
    'MATTER',
    'TASK',
    'COMPLIANCE_CYCLE',
    'NOTICE',
    'REVIEW'
);""",
        """CREATE TYPE public.assignmentaction AS ENUM (
    'ASSIGN',
    'REASSIGN',
    'UNASSIGN',
    'TEAM_ASSIGN',
    'ESCALATE',
    'DE_ESCALATE'
);""",
        """CREATE TYPE public.auditaction AS ENUM (
    'CREATE',
    'READ',
    'UPDATE',
    'DELETE',
    'LOGIN',
    'LOGOUT',
    'PASSWORD_CHANGE',
    'PERMISSION_CHANGE',
    'ROLE_CHANGE',
    'TENANT_SWITCH',
    'EXPORT',
    'IMPORT',
    'BULK_ACTION',
    'STATUS_CHANGE',
    'ASSIGN',
    'UNASSIGN',
    'ARCHIVE',
    'UNARCHIVE',
    'SEND',
    'RECEIVE',
    'APPROVE',
    'REJECT',
    'REWORK',
    'COMPLETE',
    'FILE',
    'PAY',
    'REFUND'
);""",
        """CREATE TYPE public.clientcategory AS ENUM (
    'INDIVIDUAL',
    'COMPANY',
    'LLP',
    'PARTNERSHIP',
    'HUF',
    'TRUST',
    'AOP',
    'BOI',
    'GOVERNMENT',
    'NON_PROFIT',
    'FOREIGN',
    'OTHER'
);""",
        """CREATE TYPE public.clientstatus AS ENUM (
    'ACTIVE',
    'INACTIVE',
    'ARCHIVED',
    'ONBOARDING',
    'PROSPECT'
);""",
        """CREATE TYPE public.commentableentitytype AS ENUM (
    'MATTER',
    'TASK',
    'DOCUMENT',
    'NOTICE',
    'REVIEW',
    'CLIENT',
    'COMPLIANCE_CYCLE',
    'MCA_CYCLE',
    'TDS_CYCLE'
);""",
        """CREATE TYPE public.commenttype AS ENUM (
    'COMMENT',
    'INTERNAL_NOTE',
    'MENTION',
    'SYSTEM'
);""",
        """CREATE TYPE public.communicationchannel AS ENUM (
    'EMAIL',
    'WHATSAPP',
    'SMS',
    'CALL',
    'NOTE',
    'MEETING',
    'LETTER',
    'PORTAL'
);""",
        """CREATE TYPE public.communicationdirection AS ENUM (
    'INBOUND',
    'OUTBOUND',
    'INTERNAL'
);""",
        """CREATE TYPE public.communicationstatus AS ENUM (
    'DRAFT',
    'QUEUED',
    'SENDING',
    'SENT',
    'DELIVERED',
    'READ',
    'REPLIED',
    'FAILED',
    'BOUNCED',
    'SPAM',
    'ARCHIVED'
);""",
        """CREATE TYPE public.compliancefrequency AS ENUM (
    'MONTHLY',
    'QUARTERLY',
    'ANNUAL',
    'HALF_YEARLY',
    'EVENT_BASED'
);""",
        """CREATE TYPE public.compliancestatus AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'READY_FOR_REVIEW',
    'REWORK',
    'APPROVED',
    'FILED',
    'COMPLETED',
    'OVERDUE',
    'CANCELLED'
);""",
        """CREATE TYPE public.documentcategory AS ENUM (
    'KYC',
    'FINANCIAL',
    'TAX',
    'LEGAL',
    'CORPORATE',
    'COMPLIANCE',
    'CORRESPONDENCE',
    'CONTRACT',
    'INVOICE',
    'RECEIPT',
    'BANK_STATEMENT',
    'OTHER'
);""",
        """CREATE TYPE public.documentstatus AS ENUM (
    'UPLOADED',
    'PROCESSING',
    'PROCESSED',
    'FAILED',
    'ARCHIVED',
    'QUARANTINED'
);""",
        """CREATE TYPE public.escalationreason AS ENUM (
    'OVERDUE',
    'WORKLOAD',
    'EXPERTISE',
    'UNAVAILABLE',
    'PRIORITY',
    'SLA_BREACH',
    'MANUAL'
);""",
        """CREATE TYPE public.eventtype AS ENUM (
    'COMPLIANCE_DEADLINE',
    'TASK_DEADLINE',
    'NOTICE_DEADLINE',
    'CLIENT_MEETING',
    'INTERNAL_MEETING',
    'HEARING',
    'FOLLOW_UP',
    'REVIEW_MEETING',
    'TRAINING',
    'LEAVE',
    'HOLIDAY',
    'OTHER'
);""",
        """CREATE TYPE public.expensestatus AS ENUM (
    'DRAFT',
    'SUBMITTED',
    'APPROVED',
    'REJECTED',
    'REIMBURSED',
    'PAID'
);""",
        """CREATE TYPE public.invoicestatus AS ENUM (
    'DRAFT',
    'SENT',
    'PARTIAL',
    'PAID',
    'OVERDUE',
    'CANCELLED',
    'REFUNDED'
);""",
        """CREATE TYPE public.matterpriority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'URGENT',
    'CRITICAL'
);""",
        """CREATE TYPE public.matterstatus AS ENUM (
    'CREATED',
    'INFORMATION_PENDING',
    'IN_PROGRESS',
    'READY_FOR_REVIEW',
    'REWORK',
    'APPROVED',
    'FILED',
    'BILLING_FOLLOWUP',
    'CLOSED'
);""",
        """CREATE TYPE public.mattertype AS ENUM (
    'ITR',
    'GST',
    'TDS',
    'MCA_ROC',
    'AUDIT',
    'ACCOUNTING',
    'ADVISORY',
    'LEGAL',
    'SECRETARIAL',
    'VALUATION',
    'OTHER'
);""",
        """CREATE TYPE public.mcaentitytype AS ENUM (
    'COMPANY',
    'LLP'
);""",
        """CREATE TYPE public.mcafilingcategory AS ENUM (
    'ANNUAL',
    'EVENT_BASED',
    'OTHER'
);""",
        """CREATE TYPE public.mcafilingtype AS ENUM (
    'AOC_4',
    'AOC_4_XBRL',
    'MGT_7',
    'MGT_7A',
    'ADT_1',
    'DPT_3',
    'MSME_1',
    'DIR_3_KYC',
    'FORM_8',
    'FORM_11',
    'FORM_3',
    'FORM_4',
    'SH_7',
    'SH_8',
    'MGT_14',
    'PAS_3',
    'DIR_12',
    'INC_22',
    'INC_28',
    'OTHER'
);""",
        """CREATE TYPE public.mcastatus AS ENUM (
    'PENDING',
    'DOCUMENT_COLLECTION',
    'PREPARATION',
    'REVIEW',
    'BOARD_APPROVAL',
    'AGM_COMPLETED',
    'READY_FOR_FILING',
    'FILED',
    'APPROVED',
    'REJECTED',
    'DEFECTIVE',
    'RESUBMITTED',
    'COMPLETED',
    'OVERDUE',
    'CANCELLED'
);""",
        """CREATE TYPE public.noticeauthority AS ENUM (
    'INCOME_TAX',
    'GST',
    'MCA',
    'ROC',
    'CUSTOMS',
    'PROVIDENT_FUND',
    'ESI',
    'LABOUR',
    'POLLUTION_CONTROL',
    'FIRE_DEPT',
    'MUNICIPAL',
    'POLICE',
    'COURT',
    'TRIBUNAL',
    'OTHER'
);""",
        """CREATE TYPE public.noticepriority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'URGENT',
    'CRITICAL'
);""",
        """CREATE TYPE public.noticestatus AS ENUM (
    'RECEIVED',
    'ACKNOWLEDGED',
    'UNDER_REVIEW',
    'RESPONSE_DRAFTING',
    'RESPONSE_REVIEW',
    'RESPONSE_APPROVED',
    'RESPONDED',
    'HEARING_SCHEDULED',
    'HEARING_COMPLETED',
    'ORDER_RECEIVED',
    'APPEAL_FILED',
    'CLOSED',
    'ESCALATED'
);""",
        """CREATE TYPE public.noticetype AS ENUM (
    'SHOW_CAUSE',
    'DEMAND',
    'SCRUTINY',
    'ASSESSMENT',
    'PENALTY',
    'PROSECUTION',
    'SUMMONS',
    'INQUIRY',
    'SURVEY',
    'SEARCH',
    'SEIZURE',
    'RECTIFICATION',
    'APPEAL',
    'REVISION',
    'REFUND',
    'INTIMATION',
    'COMPLIANCE',
    'OTHER'
);""",
        """CREATE TYPE public.notificationchannel AS ENUM (
    'IN_APP',
    'EMAIL',
    'SMS',
    'WHATSAPP',
    'PUSH'
);""",
        """CREATE TYPE public.notificationpriority AS ENUM (
    'LOW',
    'NORMAL',
    'HIGH',
    'URGENT'
);""",
        """CREATE TYPE public.notificationstatus AS ENUM (
    'PENDING',
    'SENT',
    'DELIVERED',
    'READ',
    'FAILED',
    'DISMISSED'
);""",
        """CREATE TYPE public.notificationtrigger AS ENUM (
    'ASSIGNMENT',
    'REASSIGNMENT',
    'DEADLINE_APPROACHING',
    'DEADLINE_OVERDUE',
    'REVIEW_REQUEST',
    'REVIEW_APPROVED',
    'REVIEW_REJECTED',
    'REVIEW_REWORK',
    'MENTION',
    'ESCALATION',
    'COMMENT',
    'STATUS_CHANGE',
    'DOCUMENT_UPLOADED',
    'COMPLIANCE_DUE',
    'NOTICE_RECEIVED',
    'CUSTOM'
);""",
        """CREATE TYPE public.paymentstatus AS ENUM (
    'PENDING',
    'COMPLETED',
    'FAILED',
    'REFUNDED',
    'BOUNCED'
);""",
        """CREATE TYPE public.reviewstage AS ENUM (
    'DRAFT',
    'SUBMITTED',
    'UNDER_REVIEW',
    'APPROVED',
    'REJECTED',
    'REWORK',
    'ESCALATED'
);""",
        """CREATE TYPE public.reviewstatus AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'COMPLETED',
    'CANCELLED'
);""",
        """CREATE TYPE public.reviewtype AS ENUM (
    'MATTER',
    'COMPLIANCE',
    'NOTICE',
    'DOCUMENT',
    'AUDIT_WORKPAPER',
    'TASK',
    'CUSTOM'
);""",
        """CREATE TYPE public.taskpriority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'URGENT',
    'CRITICAL'
);""",
        """CREATE TYPE public.taskstatus AS ENUM (
    'TODO',
    'IN_PROGRESS',
    'IN_REVIEW',
    'REWORK',
    'COMPLETED',
    'CANCELLED',
    'ON_HOLD'
);""",
        """CREATE TYPE public.tdschallanstatus AS ENUM (
    'PENDING',
    'PAID',
    'VERIFIED',
    'MISMATCH'
);""",
        """CREATE TYPE public.tdsdeducteetype AS ENUM (
    'SALARY',
    'NON_SALARY',
    'NRI',
    'TCS'
);""",
        """CREATE TYPE public.tdsformtype AS ENUM (
    'FORM_24Q',
    'FORM_26Q',
    'FORM_27Q',
    'FORM_27EQ'
);""",
        """CREATE TYPE public.tdsquarter AS ENUM (
    'Q1',
    'Q2',
    'Q3',
    'Q4'
);""",
        """CREATE TYPE public.tdsstatus AS ENUM (
    'PENDING',
    'DATA_COLLECTION',
    'VALIDATION',
    'READY_FOR_FILING',
    'FILED',
    'PROCESSED',
    'DEFAULTER',
    'CANCELLED'
);""",
        """CREATE TYPE public.workflowentitytype AS ENUM (
    'MATTER',
    'COMPLIANCE_CYCLE',
    'NOTICE',
    'REVIEW',
    'TASK',
    'AUDIT_WORKPAPER',
    'DOCUMENT'
);""",
        """CREATE TYPE public.workloadperiod AS ENUM (
    'DAILY',
    'WEEKLY',
    'MONTHLY',
    'QUARTERLY'
);""",
        """CREATE TABLE public.assignment_history (
    assignment_id uuid NOT NULL,
    action public.assignmentaction NOT NULL,
    from_user_id uuid,
    to_user_id uuid,
    from_team_id uuid,
    to_team_id uuid,
    actor_id uuid NOT NULL,
    reason text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.assignments (
    entity_type public.assignableentitytype NOT NULL,
    entity_id uuid NOT NULL,
    user_id uuid,
    team_id uuid,
    assigned_by_id uuid NOT NULL,
    assigned_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    unassigned_at timestamp with time zone,
    unassigned_by_id uuid,
    unassign_reason text,
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.audit_logs (
    user_id uuid,
    action public.auditaction NOT NULL,
    resource_type character varying(100),
    resource_id uuid,
    old_values jsonb NOT NULL,
    new_values jsonb NOT NULL,
    changed_fields character varying[] NOT NULL,
    ip_address character varying(45),
    user_agent text,
    request_id character varying(100),
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.calendar_events (
    title character varying(255) NOT NULL,
    description text,
    event_type public.eventtype NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    all_day boolean NOT NULL,
    timezone character varying(50) NOT NULL,
    location character varying(500),
    meeting_url character varying(500),
    client_id uuid,
    matter_id uuid,
    task_id uuid,
    compliance_cycle_id uuid,
    notice_id uuid,
    user_id uuid,
    attendee_ids uuid[] NOT NULL,
    reminder_minutes integer[] NOT NULL,
    is_recurring boolean NOT NULL,
    recurrence_rule character varying(500),
    recurrence_end timestamp with time zone,
    color character varying(7),
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.client_contacts (
    client_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    designation character varying(100),
    email character varying(255),
    phone character varying(20),
    mobile character varying(20),
    is_primary boolean NOT NULL,
    department character varying(100),
    notes text,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.client_services (
    client_id uuid NOT NULL,
    service_type character varying(100) NOT NULL,
    service_name character varying(255),
    description text,
    is_active boolean NOT NULL,
    start_date timestamp with time zone,
    end_date timestamp with time zone,
    billing_frequency character varying(50),
    billing_amount double precision,
    responsible_user_id uuid,
    responsible_team_id uuid,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.clients (
    name character varying(255) NOT NULL,
    display_name character varying(255),
    category public.clientcategory NOT NULL,
    status public.clientstatus NOT NULL,
    pan character varying(10),
    gstin character varying(15),
    tan character varying(10),
    cin character varying(21),
    din character varying(8),
    aadhaar character varying(12),
    passport character varying(20),
    other_ids jsonb NOT NULL,
    address text,
    city character varying(100),
    state character varying(100),
    pincode character varying(10),
    country character varying(100) NOT NULL,
    email character varying(255),
    phone character varying(20),
    website character varying(255),
    responsible_user_id uuid,
    responsible_team_id uuid,
    notes text,
    tags character varying[] NOT NULL,
    extra_metadata jsonb NOT NULL,
    is_archived boolean NOT NULL,
    archived_at timestamp with time zone,
    archived_by uuid,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.comment_attachments (
    comment_id uuid NOT NULL,
    filename character varying(500) NOT NULL,
    file_size integer NOT NULL,
    mime_type character varying(100) NOT NULL,
    storage_path character varying(1000) NOT NULL,
    storage_provider character varying(50) NOT NULL,
    storage_key character varying(500) NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.comment_reactions (
    comment_id uuid NOT NULL,
    user_id uuid NOT NULL,
    reaction_type character varying(20) NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.comments (
    entity_type public.commentableentitytype NOT NULL,
    entity_id uuid NOT NULL,
    author_id uuid NOT NULL,
    content text NOT NULL,
    comment_type public.commenttype NOT NULL,
    parent_comment_id uuid,
    mentions uuid[] NOT NULL,
    is_edited boolean NOT NULL,
    edited_at timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.communications (
    client_id uuid NOT NULL,
    matter_id uuid,
    task_id uuid,
    campaign_id uuid,
    channel public.communicationchannel NOT NULL,
    direction public.communicationdirection NOT NULL,
    status public.communicationstatus NOT NULL,
    subject character varying(500),
    body text NOT NULL,
    body_html text,
    from_address character varying(255),
    to_addresses character varying[] NOT NULL,
    cc_addresses character varying[] NOT NULL,
    bcc_addresses character varying[] NOT NULL,
    thread_id uuid,
    parent_communication_id uuid,
    conversation_id uuid,
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    read_at timestamp with time zone,
    provider character varying(50),
    provider_message_id character varying(255),
    provider_status character varying(50),
    provider_response jsonb NOT NULL,
    attachment_ids uuid[] NOT NULL,
    linked_document_ids uuid[] NOT NULL,
    linked_task_ids uuid[] NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.compliance_applicability (
    client_id uuid NOT NULL,
    compliance_type_id uuid NOT NULL,
    is_applicable boolean NOT NULL,
    applicability_reason text,
    auto_generate_cycles boolean NOT NULL,
    custom_frequency public.compliancefrequency,
    custom_due_date_rules jsonb NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.compliance_cycles (
    client_id uuid NOT NULL,
    compliance_type_id uuid NOT NULL,
    matter_id uuid,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    extended_due_date timestamp with time zone,
    filing_date timestamp with time zone,
    status public.compliancestatus NOT NULL,
    priority character varying(20) NOT NULL,
    assigned_user_id uuid,
    assigned_team_id uuid,
    checklist jsonb[] NOT NULL,
    document_requirements jsonb[] NOT NULL,
    workflow_stage character varying(100),
    workflow_stages jsonb[] NOT NULL,
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.compliance_types (
    code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    category character varying(100) NOT NULL,
    frequency public.compliancefrequency NOT NULL,
    applicability_rules jsonb NOT NULL,
    due_date_rules jsonb NOT NULL,
    period_rules jsonb NOT NULL,
    default_checklist jsonb[] NOT NULL,
    default_document_requirements jsonb[] NOT NULL,
    default_workflow_stages jsonb[] NOT NULL,
    default_assignment_rules jsonb NOT NULL,
    reminder_schedule jsonb[] NOT NULL,
    escalation_rules jsonb[] NOT NULL,
    is_active boolean NOT NULL,
    is_system boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.documents (
    client_id uuid NOT NULL,
    matter_id uuid,
    task_id uuid,
    compliance_cycle_id uuid,
    filename character varying(500) NOT NULL,
    original_filename character varying(500) NOT NULL,
    file_extension character varying(20) NOT NULL,
    mime_type character varying(100) NOT NULL,
    file_size numeric(20,0) NOT NULL,
    storage_path character varying(1000) NOT NULL,
    storage_provider character varying(50) NOT NULL,
    storage_bucket character varying(100),
    storage_key character varying(500) NOT NULL,
    version integer NOT NULL,
    is_latest_version boolean NOT NULL,
    previous_version_id uuid,
    category public.documentcategory NOT NULL,
    status public.documentstatus NOT NULL,
    title character varying(255),
    description text,
    tags character varying[] NOT NULL,
    uploaded_by uuid NOT NULL,
    source character varying(50) NOT NULL,
    source_communication_id uuid,
    checksum character varying(128),
    ocr_text text,
    extracted_data jsonb NOT NULL,
    classification character varying(100),
    confidence_score numeric(5,4),
    retention_policy character varying(100),
    retention_until timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.escalations (
    entity_type public.assignableentitytype NOT NULL,
    entity_id uuid NOT NULL,
    escalated_from_id uuid,
    escalated_to_id uuid NOT NULL,
    escalated_by_id uuid NOT NULL,
    reason public.escalationreason NOT NULL,
    description text NOT NULL,
    previous_assignee_id uuid,
    previous_team_id uuid,
    is_resolved boolean NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by_id uuid,
    resolution_notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.expenses (
    client_id uuid,
    matter_id uuid,
    user_id uuid NOT NULL,
    expense_number character varying(100) NOT NULL,
    expense_date timestamp with time zone NOT NULL,
    amount numeric(15,2) NOT NULL,
    currency character varying(3) NOT NULL,
    status public.expensestatus NOT NULL,
    category character varying(100) NOT NULL,
    description text NOT NULL,
    vendor character varying(255),
    receipt_url character varying(500),
    is_billable boolean NOT NULL,
    is_reimbursable boolean NOT NULL,
    approved_by uuid,
    approved_at timestamp with time zone,
    reimbursed_at timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.firms (
    name character varying(255) NOT NULL,
    display_name character varying(255),
    registration_number character varying(100),
    gstin character varying(15),
    pan character varying(10),
    address text,
    city character varying(100),
    state character varying(100),
    pincode character varying(10),
    country character varying(100) NOT NULL,
    phone character varying(20),
    email character varying(255),
    website character varying(255),
    logo_url character varying(500),
    is_active boolean NOT NULL,
    settings jsonb NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);""",
        """CREATE TABLE public.invoice_items (
    invoice_id uuid NOT NULL,
    description character varying(500) NOT NULL,
    quantity numeric(10,2) NOT NULL,
    unit_price numeric(15,2) NOT NULL,
    tax_rate numeric(5,2) NOT NULL,
    discount numeric(15,2) NOT NULL,
    total numeric(15,2) NOT NULL,
    service_type character varying(100),
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    time_entry_id uuid,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.invoices (
    client_id uuid NOT NULL,
    matter_id uuid,
    invoice_number character varying(100) NOT NULL,
    invoice_date timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    status public.invoicestatus NOT NULL,
    subtotal numeric(15,2) NOT NULL,
    tax_amount numeric(15,2) NOT NULL,
    discount_amount numeric(15,2) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    paid_amount numeric(15,2) NOT NULL,
    balance_amount numeric(15,2) NOT NULL,
    currency character varying(3) NOT NULL,
    notes text,
    terms text,
    sent_at timestamp with time zone,
    paid_at timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.matters (
    client_id uuid NOT NULL,
    matter_type public.mattertype NOT NULL,
    status public.matterstatus NOT NULL,
    priority public.matterpriority NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    matter_number character varying(100),
    service_id uuid,
    compliance_cycle_id uuid,
    responsible_user_id uuid,
    responsible_team_id uuid,
    start_date timestamp with time zone,
    due_date timestamp with time zone,
    completed_date timestamp with time zone,
    estimated_hours numeric(10,2),
    actual_hours numeric(10,2),
    progress_percentage integer NOT NULL,
    tags character varying[] NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.mca_filing_configs (
    filing_type public.mcafilingtype NOT NULL,
    entity_type public.mcaentitytype NOT NULL,
    filing_category public.mcafilingcategory NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    form_name character varying(100) NOT NULL,
    due_date_rule jsonb NOT NULL,
    period_rule jsonb NOT NULL,
    is_annual boolean NOT NULL,
    default_checklist jsonb[] NOT NULL,
    default_document_requirements jsonb[] NOT NULL,
    default_workflow_stages jsonb[] NOT NULL,
    base_fee double precision NOT NULL,
    additional_fee_per_day double precision NOT NULL,
    max_additional_fee double precision NOT NULL,
    is_active boolean NOT NULL,
    is_system boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.mca_filing_cycles (
    client_id uuid NOT NULL,
    compliance_cycle_id uuid,
    matter_id uuid,
    workflow_instance_id uuid,
    entity_type public.mcaentitytype NOT NULL,
    filing_type public.mcafilingtype NOT NULL,
    filing_category public.mcafilingcategory NOT NULL,
    financial_year character varying(9),
    event_date timestamp with time zone,
    event_description text,
    period_start timestamp with time zone,
    period_end timestamp with time zone,
    due_date timestamp with time zone NOT NULL,
    extended_due_date timestamp with time zone,
    agm_date timestamp with time zone,
    filing_date timestamp with time zone,
    approval_date timestamp with time zone,
    status public.mcastatus NOT NULL,
    priority character varying(20) NOT NULL,
    assigned_user_id uuid,
    assigned_team_id uuid,
    cin_llpin character varying(21),
    company_name character varying(255),
    roc_code character varying(10),
    srn character varying(50),
    acknowledgment_number character varying(50),
    challan_amount double precision NOT NULL,
    additional_fee double precision NOT NULL,
    checklist jsonb[] NOT NULL,
    document_requirements jsonb[] NOT NULL,
    workflow_stages jsonb[] NOT NULL,
    missing_info jsonb[] NOT NULL,
    missing_info_count integer NOT NULL,
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notice_escalations (
    notice_id uuid NOT NULL,
    escalated_from_id uuid,
    escalated_to_id uuid NOT NULL,
    escalated_by_id uuid NOT NULL,
    reason text NOT NULL,
    previous_deadline timestamp with time zone,
    new_deadline timestamp with time zone,
    is_resolved boolean NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by uuid,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notices (
    client_id uuid NOT NULL,
    matter_id uuid,
    workflow_instance_id uuid,
    authority public.noticeauthority NOT NULL,
    authority_name character varying(255),
    reference_number character varying(100) NOT NULL,
    notice_type public.noticetype NOT NULL,
    subject character varying(500) NOT NULL,
    description text,
    received_date timestamp with time zone NOT NULL,
    notice_date timestamp with time zone,
    response_deadline timestamp with time zone NOT NULL,
    extended_deadline timestamp with time zone,
    status public.noticestatus NOT NULL,
    priority public.noticepriority NOT NULL,
    assignee_id uuid,
    team_id uuid,
    escalated_to_id uuid,
    demand_amount double precision,
    penalty_amount double precision,
    interest_amount double precision,
    total_amount double precision,
    response_draft text,
    response_filed_date timestamp with time zone,
    response_acknowledgment character varying(100),
    response_mode character varying(50),
    outcome text,
    order_date timestamp with time zone,
    order_summary text,
    appeal_filed boolean NOT NULL,
    appeal_details text,
    closed_at timestamp with time zone,
    closed_by uuid,
    closure_reason text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notification_deliveries (
    notification_id uuid NOT NULL,
    channel public.notificationchannel NOT NULL,
    recipient_address character varying(500),
    subject character varying(500),
    content text NOT NULL,
    status public.notificationstatus NOT NULL,
    sent_at timestamp with time zone,
    delivered_at timestamp with time zone,
    failed_at timestamp with time zone,
    error_message text,
    provider_response jsonb NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notification_preferences (
    user_id uuid NOT NULL,
    trigger public.notificationtrigger NOT NULL,
    channel public.notificationchannel NOT NULL,
    is_enabled boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notification_templates (
    code character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    trigger public.notificationtrigger NOT NULL,
    channels character varying[] NOT NULL,
    subject_template text NOT NULL,
    body_template text NOT NULL,
    default_priority public.notificationpriority NOT NULL,
    is_active boolean NOT NULL,
    is_system boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.notifications (
    recipient_id uuid NOT NULL,
    trigger public.notificationtrigger NOT NULL,
    template_id uuid,
    title character varying(500) NOT NULL,
    message text NOT NULL,
    priority public.notificationpriority NOT NULL,
    entity_type character varying(50),
    entity_id uuid,
    actor_id uuid,
    channels character varying[] NOT NULL,
    channel_status jsonb NOT NULL,
    status public.notificationstatus NOT NULL,
    read_at timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.payments (
    client_id uuid NOT NULL,
    invoice_id uuid,
    payment_number character varying(100) NOT NULL,
    payment_date timestamp with time zone NOT NULL,
    amount numeric(15,2) NOT NULL,
    status public.paymentstatus NOT NULL,
    method character varying(50),
    reference character varying(100),
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.review_comments (
    review_request_id uuid NOT NULL,
    author_id uuid NOT NULL,
    content text NOT NULL,
    is_internal boolean NOT NULL,
    mentions uuid[] NOT NULL,
    parent_comment_id uuid,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.review_history (
    review_request_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    action character varying(50) NOT NULL,
    from_stage character varying(50),
    to_stage character varying(50),
    from_status character varying(50),
    to_status character varying(50),
    comment text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.review_requests (
    source_object_type public.reviewtype NOT NULL,
    source_object_id uuid NOT NULL,
    workflow_instance_id uuid,
    title character varying(500) NOT NULL,
    description text,
    stage public.reviewstage NOT NULL,
    status public.reviewstatus NOT NULL,
    reviewer_id uuid,
    reviewer_team_id uuid,
    submitted_by_id uuid,
    submitted_at timestamp with time zone,
    due_date timestamp with time zone,
    completed_at timestamp with time zone,
    priority character varying(20) NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.tasks (
    client_id uuid,
    matter_id uuid,
    parent_task_id uuid,
    title character varying(500) NOT NULL,
    description text,
    task_number character varying(100),
    status public.taskstatus NOT NULL,
    priority public.taskpriority NOT NULL,
    assignee_id uuid,
    team_id uuid,
    reporter_id uuid,
    due_date timestamp with time zone,
    start_date timestamp with time zone,
    completed_date timestamp with time zone,
    estimated_hours numeric(10,2),
    actual_hours numeric(10,2),
    progress_percentage integer NOT NULL,
    checklist jsonb NOT NULL,
    dependencies uuid[] NOT NULL,
    tags character varying[] NOT NULL,
    extra_metadata jsonb NOT NULL,
    source_communication_id uuid,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.tds_challans (
    tds_cycle_id uuid NOT NULL,
    cin character varying(50) NOT NULL,
    bsr_code character varying(7) NOT NULL,
    deposit_date timestamp with time zone NOT NULL,
    challan_serial character varying(5) NOT NULL,
    tax_amount numeric(15,2) NOT NULL,
    surcharge numeric(15,2) NOT NULL,
    education_cess numeric(15,2) NOT NULL,
    interest numeric(15,2) NOT NULL,
    penalty numeric(15,2) NOT NULL,
    fee numeric(15,2) NOT NULL,
    total_amount numeric(15,2) NOT NULL,
    status public.tdschallanstatus NOT NULL,
    verified_at timestamp with time zone,
    verified_by uuid,
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.tds_compliance_cycles (
    client_id uuid NOT NULL,
    compliance_cycle_id uuid,
    matter_id uuid,
    workflow_instance_id uuid,
    form_type public.tdsformtype NOT NULL,
    financial_year character varying(9) NOT NULL,
    quarter public.tdsquarter NOT NULL,
    period_start timestamp with time zone NOT NULL,
    period_end timestamp with time zone NOT NULL,
    due_date timestamp with time zone NOT NULL,
    extended_due_date timestamp with time zone,
    filing_date timestamp with time zone,
    processed_date timestamp with time zone,
    status public.tdsstatus NOT NULL,
    priority character varying(20) NOT NULL,
    assigned_user_id uuid,
    assigned_team_id uuid,
    tan character varying(20),
    total_deductees integer NOT NULL,
    total_tax_deducted numeric(15,2) NOT NULL,
    total_tax_deposited numeric(15,2) NOT NULL,
    token_number character varying(50),
    acknowledgment_number character varying(50),
    checklist jsonb[] NOT NULL,
    document_requirements jsonb[] NOT NULL,
    workflow_stages jsonb[] NOT NULL,
    missing_info jsonb[] NOT NULL,
    missing_info_count integer NOT NULL,
    notes text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.tds_deductees (
    tds_cycle_id uuid NOT NULL,
    deductee_type public.tdsdeducteetype NOT NULL,
    deductee_name character varying(255) NOT NULL,
    deductee_pan character varying(20) NOT NULL,
    deductee_address text,
    section_code character varying(10) NOT NULL,
    amount_paid numeric(15,2) NOT NULL,
    tax_deducted numeric(15,2) NOT NULL,
    tax_deposited numeric(15,2) NOT NULL,
    deduction_date timestamp with time zone NOT NULL,
    deposit_date timestamp with time zone,
    certificate_number character varying(50),
    remarks text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.team_capacity (
    team_id uuid NOT NULL,
    period_type public.workloadperiod NOT NULL,
    period_start date NOT NULL,
    period_end date NOT NULL,
    total_capacity_hours numeric(10,2) NOT NULL,
    allocated_hours numeric(10,2) NOT NULL,
    available_hours numeric(10,2) NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.teams (
    name character varying(255) NOT NULL,
    description text,
    department character varying(100),
    specialization character varying[] NOT NULL,
    is_active boolean NOT NULL,
    lead_id uuid,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.user_availability (
    user_id uuid NOT NULL,
    date date NOT NULL,
    is_available boolean NOT NULL,
    available_hours numeric(4,2) NOT NULL,
    reason text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.users (
    email character varying(255) NOT NULL,
    hashed_password character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    phone character varying(20),
    avatar_url character varying(500),
    is_active boolean NOT NULL,
    is_superuser boolean NOT NULL,
    roles character varying[] NOT NULL,
    direct_permissions character varying[] NOT NULL,
    department character varying(100),
    designation character varying(100),
    employee_id character varying(50),
    date_of_joining timestamp with time zone,
    last_login_at timestamp with time zone,
    tenant_id uuid NOT NULL,
    team_id uuid,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workflow_definitions (
    code character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    entity_type public.workflowentitytype NOT NULL,
    version integer NOT NULL,
    initial_state character varying(100) NOT NULL,
    states jsonb[] NOT NULL,
    transitions jsonb[] NOT NULL,
    is_active boolean NOT NULL,
    is_default boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workflow_instances (
    workflow_definition_id uuid NOT NULL,
    entity_type public.workflowentitytype NOT NULL,
    entity_id uuid NOT NULL,
    current_state character varying(100) NOT NULL,
    previous_state character varying(100),
    assigned_user_id uuid,
    assigned_team_id uuid,
    context_data jsonb NOT NULL,
    is_active boolean NOT NULL,
    completed_at timestamp with time zone,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workflow_transition_definitions (
    workflow_definition_id uuid NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    from_state character varying(100) NOT NULL,
    to_state character varying(100) NOT NULL,
    required_permissions character varying[] NOT NULL,
    required_roles character varying[] NOT NULL,
    conditions jsonb NOT NULL,
    auto_transition boolean NOT NULL,
    auto_transition_delay integer,
    is_active boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workflow_transition_history (
    workflow_instance_id uuid NOT NULL,
    transition_definition_id uuid,
    from_state character varying(100) NOT NULL,
    to_state character varying(100) NOT NULL,
    transition_code character varying(100),
    actor_id uuid NOT NULL,
    actor_team_id uuid,
    comment text,
    reason text,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workload_snapshots (
    user_id uuid,
    team_id uuid,
    snapshot_date date NOT NULL,
    period_type public.workloadperiod NOT NULL,
    open_tasks integer NOT NULL,
    overdue_tasks integer NOT NULL,
    due_this_week integer NOT NULL,
    due_next_week integer NOT NULL,
    assigned_matters integer NOT NULL,
    active_matters integer NOT NULL,
    overdue_matters integer NOT NULL,
    estimated_hours numeric(10,2) NOT NULL,
    actual_hours numeric(10,2) NOT NULL,
    available_hours numeric(10,2) NOT NULL,
    utilization_percentage numeric(5,2) NOT NULL,
    pending_compliance integer NOT NULL,
    overdue_compliance integer NOT NULL,
    pending_notices integer NOT NULL,
    overdue_notices integer NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """CREATE TABLE public.workload_summaries (
    user_id uuid,
    team_id uuid,
    summary_date date NOT NULL,
    current_open_tasks integer NOT NULL,
    current_overdue_tasks integer NOT NULL,
    current_assigned_matters integer NOT NULL,
    current_active_matters integer NOT NULL,
    tasks_due_today integer NOT NULL,
    tasks_due_this_week integer NOT NULL,
    tasks_due_next_week integer NOT NULL,
    matters_due_this_week integer NOT NULL,
    matters_due_next_week integer NOT NULL,
    estimated_hours_this_week numeric(10,2) NOT NULL,
    actual_hours_this_week numeric(10,2) NOT NULL,
    available_hours_this_week numeric(10,2) NOT NULL,
    pending_compliance_this_week integer NOT NULL,
    overdue_compliance integer NOT NULL,
    pending_notices integer NOT NULL,
    overdue_notices integer NOT NULL,
    capacity_utilization numeric(5,2) NOT NULL,
    is_overloaded boolean NOT NULL,
    extra_metadata jsonb NOT NULL,
    tenant_id uuid NOT NULL,
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by uuid,
    updated_by uuid
);""",
        """ALTER TABLE ONLY public.assignment_history
    ADD CONSTRAINT assignment_history_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.assignments
    ADD CONSTRAINT assignments_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.calendar_events
    ADD CONSTRAINT calendar_events_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.client_contacts
    ADD CONSTRAINT client_contacts_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.client_services
    ADD CONSTRAINT client_services_pkey PRIMARY KEY (id);""",
        """ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);""",
    ]:
        op.execute(stmt)

def downgrade() -> None:
    pass