import hashlib
import logging
from datetime import UTC, datetime, timedelta
from uuid import UUID

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions import ConflictException, NotFoundException, StorageException, ValidationException
from app.core.security.malware_scanner import get_malware_scanner, MalwareScanResult
from app.core.storage.azure_blob import get_azure_blob_service
from app.modules.clients.models import Client
from app.modules.compliance.models import ComplianceCycle
from app.modules.documents.models import Document, DocumentCategory, DocumentStatus
from app.modules.documents.repository import DocumentRepository
from app.modules.documents.schemas import (
    DocumentUpdate,
    DocumentUploadCompleteRequest,
    DocumentUploadInitRequest,
    DocumentUploadInitResponse,
)
from app.modules.matters.models import Matter
from app.modules.tasks.models import Task
from app.modules.outbox.service import get_outbox_service
from app.modules.outbox.models import OutboxEventType

logger = logging.getLogger(__name__)


class DocumentService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repository = DocumentRepository(db)
        self.blob_service = get_azure_blob_service()
        self.malware_scanner = get_malware_scanner()

    async def init_upload(self, data: DocumentUploadInitRequest, tenant_id: UUID, uploaded_by: UUID) -> DocumentUploadInitResponse:
        client_result = await self.db.execute(
            select(Client).where(Client.id == data.client_id, Client.tenant_id == tenant_id)
        )
        if not client_result.scalar_one_or_none():
            raise NotFoundException(detail="Client not found")

        if data.matter_id:
            matter_result = await self.db.execute(
                select(Matter).where(Matter.id == data.matter_id, Matter.tenant_id == tenant_id)
            )
            if not matter_result.scalar_one_or_none():
                raise NotFoundException(detail="Matter not found")

        # Generate a unique document ID
        document_id = UUID(bytes=b'\x00' * 16)  # Will be generated by DB
        storage_key = f"{tenant_id}/{data.client_id}/{document_id}/{data.filename}"

        # Ensure container exists
        await self.blob_service.ensure_container_exists()

        # Generate SAS URL for upload
        upload_url = self.blob_service.generate_upload_sas_url(
            blob_name=storage_key,
            expiry_hours=1,
            content_type=data.mime_type,
        )

        # Create document record with UPLOADED status (pending actual upload)
        document = Document(
            client_id=data.client_id,
            matter_id=data.matter_id,
            filename=data.filename,
            original_filename=data.filename,
            file_extension=data.filename.split(".")[-1] if "." in data.filename else "",
            mime_type=data.mime_type,
            file_size=data.file_size,
            storage_path=storage_key,
            storage_key=storage_key,
            category=data.category,
            title=data.title,
            description=data.description,
            tags=data.tags,
            source="manual",
            uploaded_by=uploaded_by,
            tenant_id=tenant_id,
            created_by=uploaded_by,
            status=DocumentStatus.UPLOADED,
        )
        document = await self.repository.create(document)

        expires_at = datetime.now(UTC) + timedelta(hours=1)

        return DocumentUploadInitResponse(
            upload_url=upload_url,
            document_id=document.id,
            storage_key=storage_key,
            expires_at=expires_at,
        )

    async def complete_upload(
        self,
        document_id: UUID,
        tenant_id: UUID,
        checksum: str,
        uploaded_by: UUID,
    ) -> Document:
        """
        Complete the upload process:
        1. Verify blob exists in Azure Blob
        2. Verify checksum matches
        3. Download and scan for malware
        3. If clean: mark as PROCESSED
        4. If infected: quarantine and mark as QUARANTINED
        """
        document = await self.get_by_id(document_id, tenant_id)

        # Verify the blob exists in Azure Blob
        blob_exists = await self.blob_service.blob_exists(document.storage_key)
        if not blob_exists:
            document.status = DocumentStatus.FAILED
            document.extra_metadata = {**(document.extra_metadata or {}), "error": "Blob not found in storage"}
            await self.repository.update(document)
            raise StorageException("Uploaded blob not found in storage")

        # Verify checksum
        if not await self.blob_service.verify_checksum(document.storage_key, checksum):
            document.status = DocumentStatus.FAILED
            document.extra_metadata = {**(document.extra_metadata or {}), "error": "Checksum mismatch"}
            await self.repository.update(document)
            raise ValidationException("Checksum verification failed - uploaded file is corrupted or tampered")

        # Download blob for malware scanning
        try:
            blob_data = await self.blob_service.download_blob(document.storage_key)
        except StorageException as e:
            document.status = DocumentStatus.FAILED
            document.extra_metadata = {**(document.extra_metadata or {}), "error": f"Failed to download for scanning: {e}"}
            await self.repository.update(document)
            raise

        # Scan for malware
        scan_result: MalwareScanResult = self.malware_scanner.scan(blob_data, document.filename)

        document.checksum = checksum
        document.extra_metadata = {
            **(document.extra_metadata or {}),
            "malware_scan": {
                "scanned_at": datetime.now(UTC).isoformat(),
                "engine": scan_result.scan_engine,
                "scan_time_ms": scan_result.scan_time_ms,
                "infected": scan_result.is_infected,
                "malware_name": scan_result.malware_name,
            },
        }

        if scan_result.is_infected:
            # Quarantine the document
            document.status = DocumentStatus.QUARANTINED
            document.extra_metadata["malware_scan"]["quarantined_at"] = datetime.now(UTC).isoformat()
            await self.repository.update(document)

            # Optionally move blob to quarantine container
            quarantine_key = f"quarantine/{document.storage_key}"
            try:
                await self.blob_service.copy_blob(document.storage_key, quarantine_key)
                await self.blob_service.delete_blob(document.storage_key)
                document.storage_key = quarantine_key
                await self.repository.update(document)
            except Exception as e:
                logger.error(f"Failed to move infected blob to quarantine: {e}")

            raise ValidationException(f"Malware detected: {scan_result.malware_name}. Document quarantined.")

        # Clean - mark as processed
        document.status = DocumentStatus.PROCESSED
        await self.repository.update(document)

        # Emit outbox event for document upload
        from app.modules.outbox.service import get_outbox_service
        from app.modules.outbox.models import OutboxEventType
        outbox = get_outbox_service(self.db)
        await outbox.emit_event(
            tenant_id=tenant_id,
            event_type=OutboxEventType.DOCUMENT_UPLOADED,
            aggregate_type="document",
            aggregate_id=document.id,
            payload={
                "filename": document.filename,
                "file_size": document.file_size,
                "mime_type": document.mime_type,
                "checksum": checksum,
                "category": document.category.value,
            },
        )

        return document

    async def get_by_id(self, document_id: UUID, tenant_id: UUID) -> Document:
        document = await self.repository.get_by_id(document_id, tenant_id)
        if not document:
            raise NotFoundException(detail="Document not found")
        return document

    async def get_all(
        self,
        tenant_id: UUID,
        page: int = 1,
        page_size: int = 20,
        search: str | None = None,
        client_id: UUID | None = None,
        matter_id: UUID | None = None,
        task_id: UUID | None = None,
        compliance_cycle_id: UUID | None = None,
        status: DocumentStatus | None = None,
        category: DocumentCategory | None = None,
        uploaded_by: UUID | None = None,
        date_from: datetime | None = None,
        date_to: datetime | None = None,
        tags: list[str] | None = None,
        sort_by: str | None = None,
        sort_order: str = "asc",
    ) -> tuple[list[Document], int]:
        return await self.repository.get_all(
            tenant_id, page, page_size, search, client_id, matter_id, task_id,
            compliance_cycle_id, status, category, uploaded_by, date_from, date_to,
            tags, sort_by, sort_order
        )

    async def update(self, document_id: UUID, tenant_id: UUID, data: DocumentUpdate, updated_by: UUID) -> Document:
        document = await self.get_by_id(document_id, tenant_id)
        update_data = data.model_dump(exclude_unset=True)

        if update_data.get("matter_id"):
            matter_result = await self.db.execute(
                select(Matter).where(Matter.id == update_data["matter_id"], Matter.tenant_id == tenant_id)
            )
            if not matter_result.scalar_one_or_none():
                raise NotFoundException(detail="Matter not found")

        if update_data.get("task_id"):
            task_result = await self.db.execute(
                select(Task).where(Task.id == update_data["task_id"], Task.tenant_id == tenant_id)
            )
            if not task_result.scalar_one_or_none():
                raise NotFoundException(detail="Task not found")

        if update_data.get("compliance_cycle_id"):
            cycle_result = await self.db.execute(
                select(ComplianceCycle).where(ComplianceCycle.id == update_data["compliance_cycle_id"], ComplianceCycle.tenant_id == tenant_id)
            )
            if not cycle_result.scalar_one_or_none():
                raise NotFoundException(detail="Compliance cycle not found")

        for field, value in update_data.items():
            setattr(document, field, value)
        document.updated_by = updated_by
        return await self.repository.update(document)

    async def create_new_version(
        self,
        document_id: UUID,
        tenant_id: UUID,
        data: DocumentUploadInitRequest,
        uploaded_by: UUID,
    ) -> DocumentUploadInitResponse:
        old_document = await self.get_by_id(document_id, tenant_id)

        if old_document.client_id != data.client_id:
            raise ConflictException(detail="Cannot change client for new version")

        # Create new version with SAS URL
        new_version = old_document.version + 1
        storage_key = f"{tenant_id}/{data.client_id}/{old_document.id}/v{new_version}/{data.filename}"

        await self.blob_service.ensure_container_exists()
        upload_url = self.blob_service.generate_upload_sas_url(
            blob_name=storage_key,
            expiry_hours=1,
            content_type=data.mime_type,
        )

        old_document.is_latest_version = False
        await self.repository.update(old_document)

        new_document = Document(
            client_id=data.client_id,
            matter_id=data.matter_id,
            filename=data.filename,
            original_filename=data.filename,
            file_extension=data.filename.split(".")[-1] if "." in data.filename else "",
            mime_type=data.mime_type,
            file_size=data.file_size,
            storage_path=storage_key,
            storage_key=storage_key,
            category=data.category,
            title=data.title,
            description=data.description,
            tags=data.tags,
            source="manual",
            uploaded_by=uploaded_by,
            tenant_id=tenant_id,
            created_by=uploaded_by,
            status=DocumentStatus.UPLOADED,
            version=new_version,
            previous_version_id=old_document.id,
        )
        new_document = await self.repository.create_version(new_document)

        expires_at = datetime.now(UTC) + timedelta(hours=1)

        return DocumentUploadInitResponse(
            upload_url=upload_url,
            document_id=new_document.id,
            storage_key=storage_key,
            expires_at=expires_at,
        )

    async def delete(self, document_id: UUID, tenant_id: UUID) -> None:
        document = await self.get_by_id(document_id, tenant_id)
        # Delete from blob storage
        await self.blob_service.delete_blob(document.storage_key)
        await self.repository.delete(document)

    async def generate_download_url(self, document_id: UUID, tenant_id: UUID, expiry_hours: int = 1) -> str:
        document = await self.get_by_id(document_id, tenant_id)
        return self.blob_service.generate_download_sas_url(document.storage_key, expiry_hours)

    async def get_document_metadata(self, document_id: UUID, tenant_id: UUID) -> dict:
        document = await self.get_by_id(document_id, tenant_id)
        return await self.blob_service.get_blob_properties(document.storage_key)